### ISSUE TITLE
NotEmpty to allow null but dont allow no value

### ISSUE THREAD

**Issue by cbichis** [laminas/laminas-validator#111]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Is needed to allow null values as valid values but dont allow no value provided as a valid value. Currently as far as I know there is no such possibility.

By example it would be useful to run a Validator if the value provided is null...

**Comment by weierophinney** [comment]
This is highly specific functionality, and I would create a custom validator in this case, using the `Callback` validator:

```php
$validator = new Callback(function (mixed $value): bool {
    if (null === $value) {
        return true;
    }
   return ! empty($value);
});
```

**Comment by cbichis** [comment]
Thanks @weierophinney for your suggestion. Is something easily doable so I agree with your conclusion.

**Comment by cbichis** [comment]
Actually this is not good. In case we have null value the validators are not firing...

**Comment by froschdesign** [comment]
@cbichis 
Please describe your problem in the [forum](https://discourse.laminas.dev) with a code example. Then we can find a suitable solution for the callback validator.
