### ISSUE TITLE
Package container-interop/container-interop is abandoned

### ISSUE THREAD

**Issue by spbentz** [laminas/laminas-validator#114]
### BC Break Report

|    Q            |   A
|------------ | ------
| Version     |  2.15.0

#### Summary

Composer install returns:
"Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead."

**Comment by Ocramius** [comment]
Heyo,

No BC break: we are slowly migrating away from container-interop and towards psr/container, but to do so, we first have to have a BC compliant upgrade path for downstream consumers.

See https://github.com/laminas/laminas-servicemanager/pull/96
