### ISSUE TITLE
Missing Ukraine(UA) in Iban validator

### ISSUE THREAD

**Issue by Bontah** [laminas/laminas-validator#117]
### Bug Report

Ukraine is missing in the regex list for the iban validator

|    Q        |   A
|------------ | ------
| Version(s)  | 2.15.1

#### Summary

wanted to validate an ukraine iban. just found out there's no regex for ua

#### Current behavior

country code is not supported
other not supported countries:

1. El Salvador
2. Jordan
3. Qatar
4. Kosovo
5. Saint Lucia
6. São Tomé and Príncipe
7. Seychelles
8. Timor-Leste

**Comment by Ocramius** [comment]
Would you be able to send a patch?

**Comment by Bontah** [comment]
added the PR #118
took me a little while to figure out how i can submit one.
