### ISSUE TITLE
Drop Zend related aliases and anything providing compatibility with Zend

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-validator#130]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

When #129 goes in, and we're on 7.4 minimum, theoretically Zend libs can no longer be installed so it should be possible to kill off all the Zend related stuff.

**Comment by Ocramius** [comment]
IMO no: aliases are just string references, so libraries being installed or not makes no difference.

**Comment by gsteel** [comment]
OK - Feel free to close unless you want to leave the issue hanging for the next major :)

**Comment by Ocramius** [comment]
I'm fine with dropping them in the next major :+1:
