### ISSUE TITLE
Drop or upgrade Laminas\Math

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-validator#132]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Validator is stuck on Laminas\Math 2.x. It only uses it for random bytes in the CSRF validator and using v2 drags in `laminas/laminas-zendframework-bridge`.

Since PHP ^7 comes with `random_bytes`, it should be possible to drop math altogether, or alternatively upgrade to 3.x

https://github.com/laminas/laminas-validator/blob/4875d4e58b6f728981bb767a60530540f82ee1df/src/Csrf.php#L302-L318

**Comment by Ocramius** [comment]
We can use `random_bytes()` indeed :+1: 

`Rand::getBytes()` was only relevant in a pre-php7 era. /cc @ezimuel if you want to confirm that :D
