### ISSUE TITLE
GpsPoint validator needs a rewrite because it returns true for the input "foo, bar"

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-validator#135]
> I believe this validator should either be rewritten or removed entirely as it will return true for the input "foo, bar"
> 
> It expects a string as input in the form "latitude, longitude" :
> 
> ```
>     public function isValid($value)
>     {
>         if (strpos($value, ',') === false) {
>             $this->error(self::INCOMPLETE_COORDINATE, $value);
>             return false;
>         }
> 
>         [$lat, $long] = explode(',', $value);
> ```
> 
>  but the `isValidCoordinate()` method blindly casts the supposed lat or long to a double:
> 
> ```
>         $doubleLatitude = (double) $value;
> 
>         if ($doubleLatitude <= $maxBoundary && $doubleLatitude >= $maxBoundary * -1) {
>             return true;
>         }
> ```
> 
> which results in a 0 value in the case of non-numerical strings, which then passes validation as a valid lat/long.
> 
> At the very least it should have explicit comments stating that the expected input is in a very particular format already.

_Originally posted by @ajgale in https://github.com/laminas/laminas-validator/issues/69#issuecomment-1162331488_

**Comment by Ocramius** [comment]
Deprecation would be best then.

**Comment by froschdesign** [comment]
I have checked it in the unit tests and confirm the problem.

**Comment by froschdesign** [comment]
Another option would be to check if a number is included before conversion to double is done:

https://github.com/laminas/laminas-validator/blob/ba665f5a52763dda5a747c4ad826d2adf1510486/src/GpsPoint.php#L71-L78

**Comment by boesing** [comment]
Yah, using `is_numeric` should be suitable here

**Comment by froschdesign** [comment]
@boesing 
> Yah, using `is_numeric` should be suitable here

This will fail with the current test cases because coordinates like `63 47 24.691 N` are converted to `634724.691N`. The error for "out of bounds" is not set.

https://github.com/laminas/laminas-validator/blob/ba665f5a52763dda5a747c4ad826d2adf1510486/test/GPSPointTest.php#L79-L86
