### ISSUE TITLE
There's no CSRF validator documentation

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-validator#14]
zf3 documents https://docs.zendframework.com/zend-validator/ does not contains documentation about csrf.

---

Originally posted by @Zebercet at https://github.com/zendframework/zend-validator/issues/184

**Comment by settermjd** [comment]
@weierophinney, should this be changed to reference laminas-validator now? I just had a look and see that there's no documentation on the CSRF validator in laminas-validator either. So it seems still relevant.

**Comment by froschdesign** [comment]
@settermjd 
Maybe I misunderstood something, but the validator is a part of this component and the documentation is still missing.

https://github.com/laminas/laminas-validator/blob/83c2a967cd823a76a81589e895363aac73b4d646/src/Csrf.php#L16

**Comment by gsteel** [comment]
CSRF docs are now part of laminas-session https://docs.laminas.dev/laminas-session/validators/csrf/
