### ISSUE TITLE
Digits validator not working because laminas-filter dependency is not listed in `require` section of composer.json

### ISSUE THREAD

**Issue by guvra** [laminas/laminas-validator#147]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.23.0

#### Summary

The Digits validator uses `Laminas\Validator\Digits`, as shown here:
https://github.com/laminas/laminas-validator/blob/2.23.0/src/Digits.php#L5

However, the laminas-filter package is not listed in the `require` section of composer.json.

As a consequence, when this package is installed individually (e.g. with `composer require laminas/laminas-validator`, the Digits validator throws an exception when used.

#### Current behavior

The Digits validator throws the following exception:

```
Class "Laminas\Filter\Digits" not found
```

#### How to reproduce

1. Install the package laminas-validator in a project where laminas-filter is not installed:

```
composer require laminas/laminas-validator
```

2. Run the following sample code:

```php
use Laminas\Validator\Digits;

$validator = new Digits();
$validator->isValid('foo');
```

#### Expected behavior

Expected behavior: no exception thrown.

How to fix: this package must include laminas-filter in the `require` section of composer.json (instead of `require-dev`).

**Comment by froschdesign** [comment]
In the current version of this component, laminas-filter is a _soft_ dependency and therefore listed in the [suggest section of the Composer file](https://getcomposer.org/doc/04-schema.md#suggest):

https://github.com/laminas/laminas-validator/blob/3ebb924282b58aa0b0485d9fab49409fd68cc1e3/composer.json#L54-L63

The additionally required installation is also documented: https://docs.laminas.dev/laminas-validator/validators/digits/
