### ISSUE TITLE
Need support for laminas/laminas-servicemanager v4

### ISSUE THREAD

**Issue by hartois** [laminas/laminas-validator#206]
laminas/laminas-validator cannot be installed with laminas/laminas-servicemanager v4, that support psr/container v2.
Need support.

**Comment by froschdesign** [comment]
So far there is [no version 4 of laminas-servicemanager](https://github.com/laminas/laminas-servicemanager/releases). If there is a new version, then this package is also updated.

**Comment by hartois** [comment]
> So far there is [no version 4 of laminas-servicemanager](https://github.com/laminas/laminas-servicemanager/releases). If there is a new version, then this package is also updated.

RC v4 of laminas-servicemanager exists.
Now laminas-validator (and laminas-mail as example that have laminas-validator dependency) cannot be installed in projects, that need psr/container v2.

Ok, we need wait for release of laminas-servicemanager?

**Comment by boesing** [comment]
> Ok, we need wait for release of laminas-servicemanager?

No, you have to wait until compatibility is added to this package. 
ServiceManager v4 requires major versions of almost **all** components, not just validator.

There is no priority on when which package will get updated first. If you want to help, feel free to provide a patch. Happy to merge stuff even tho just adding support for SM v4 will not be the only thing we have to add for the next major.

**Comment by Zombaya** [comment]
Looks like PR #267 will solve this issue.

**Comment by gsteel** [comment]
Yes @Zombaya - it's a breaking change so it will be part of v3.0

**Comment by gsteel** [comment]
Closed via #267
