### ISSUE TITLE
Laminas Validator has an indirect dependency to laminas-db

### ISSUE THREAD

**Issue by nusphere** [laminas/laminas-validator#220]
### Bug Report

When doing an ReflectionClass for src/Db/AbstractDb.php then following fatal error occures:

Fatal error: Trait "Laminas\Db\Adapter\AdapterAwareTrait" not found in /XXX/src/Db/AbstractDb.php on line 27

|    Q        |   A
|------------ | ------
| Version(s)  | 2.44.1

#### How to reproduce

* require this package 
* reflect `src/Db/AbstractDb.php`
* error occues

#### Expected behavior

Trait should exists by adding a depencency to this package

**Comment by Ocramius** [comment]
I'd suggest:

 * deprecating the entire `Db` sub-namespace
 * moving to a different package, if there's interest
 * marking for deletion here for the next major release

**Comment by Ocramius** [comment]
BTW, "soft dependencies" have been a problem since before 2012, when these packages were migrated from ZF1 to ZF2, and then renamed to Laminas later.

The haunt the codebase because they can't just be ripped out :-\

**Comment by nusphere** [comment]
This error still exists. And precisely because it is a fatal error, this is a bug.

That doesn't mean that this bug needs to be fixed immediately. But in fact it is an error that is documented here.

**Comment by Ocramius** [comment]
Closing as per #223
