### ISSUE TITLE
Interface to add valid TLDs in Hostname validator

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-validator#23]
I recently used this validator but found it did not support .car TLD. The company I work for recently purchased such a domain and we needed to allow valid email addresses with that TLD.

I needed to extend the existing validator and also extend the EmailAddress validator to be able to reach the TLD list and then could attach the new validator in Apigility and add a list of TLDs, which were pushed onto the array in Hostname validator.

It would have been quite useful to just have a public function in Hostname validator to add to the validTlds array. That is what I am proposing to do myself.

---

Originally posted by @peterkeatingie at https://github.com/zendframework/zend-validator/issues/117

**Comment by weierophinney** [comment]
There should be no need to extend the EmailAddress validator in this case; construct an instance of your extended Hostname validator and supply it to the EmailAddress instance through configuration option `hostnameValidator` or [using the `setHostnameValidator` method](https://github.com/zendframework/zend-validator/blob/6129ebd4a421475c3b21a0b4d10929cf16c5d327/src/EmailAddress.php#L154).

Thanks to gTLDs the built-in TLD list falls out of sync with reality much more quickly than it used to when this validator was initially designed.  As far as I'm aware there is no formalized process for keeping this list up-to-date; if there isn't it would be worthwhile to formulate one.


---

Originally posted by @adamlundrigan at https://github.com/zendframework/zend-validator/issues/117#issuecomment-249675369

**Comment by simivar** [comment]
From what I see, this issue is connected with #27. In both, there is a discussion of where to keep the list of TLD.

**Comment by gsteel** [comment]
This issue should no longer be relevant - The list of gTLDs is checked once per week and updated when necessary.
