### ISSUE TITLE
Domainkey: Underscore in hostname

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-validator#27]
default._domainkey.example.com

$regexChars = [0 => '/^[a-z0-9\x2d]{1,63}$/i'];

[hostnameInvalidHostnameSchema]: The input appears to be a DNS hostname but cannot match against hostname schema for TLD 'COM'
[hostnameInvalidLocalName]: The input does not appear to be a valid local network name

---

Originally posted by @038291 at https://github.com/zendframework/zend-validator/issues/102

**Comment by weierophinney** [comment]
I second this.  Maybe some sort of option to permit this pattern?


---

Originally posted by @dapphp at https://github.com/zendframework/zend-validator/issues/102#issuecomment-237893539

**Comment by weierophinney** [comment]
Using underscores in hostnames can cause more problems on network level. See also 'Restrictions on valid hostnames'  on https://en.wikipedia.org/wiki/Hostname.

Also; actually the underscore is the uppercase for "-", as it comes when shift plus "-" are pressed. ;) All hostnames are lowercase.

---

Originally posted by @CptChaos at https://github.com/zendframework/zend-validator/issues/102#issuecomment-261938089

**Comment by weierophinney** [comment]
why it is impossible to realize optional check?


---

Originally posted by @038291 at https://github.com/zendframework/zend-validator/issues/102#issuecomment-261944964

**Comment by weierophinney** [comment]
@bacinsky all known dns of the server support validation of underscore in hostname long ago, but developers refer to RFC.

---

Originally posted by @038291 at https://github.com/zendframework/zend-validator/issues/102#issuecomment-261989835

**Comment by weierophinney** [comment]
@bacinsky You should've known in the first place that underscores are illegal characters for (sub)domainnames, so you can't expect a whole framework to bend for it, just because you want to and because you lack proper implementations. You really should read the Wikipedia article I linked before, as it clearly explaines why an underscore can't be correctly used in hostnames.

---

Originally posted by @CptChaos at https://github.com/zendframework/zend-validator/issues/102#issuecomment-262023673

**Comment by weierophinney** [comment]
@bacinsky If you've read the Wikipedia article, you've seen that underscores can be used for something else within DNS. More specific: 

> While a hostname may not contain other characters, such as the underscore character (_), other DNS names may contain the underscore. Systems such as DomainKeys and service records use the underscore as a means to assure that their special character is not confused with hostnames. For example, _http._sctp.www.example.com specifies a service pointer for an SCTP capable webserver host (www) in the domain example.com. Note that some applications (e.g. Microsoft Internet Explorer) won't work correctly if any part of the hostname contains an underscore character.

So my actual advice is to proper implement things like they were intended to, to avoid problems later on.
As hostnames officially can't have underscores, I'd return an error, stating underscores are not allowed, rather than try to look for options to work around it, hoping to fix it (what you did).

---

Originally posted by @CptChaos at https://github.com/zendframework/zend-validator/issues/102#issuecomment-262208384

**Comment by weierophinney** [comment]
@CptChaos  "underscore can't be correctly used in hostnames" - please proof. DKIM,DMARC,SRV,TLSA - properly works.

---

Originally posted by @038291 at https://github.com/zendframework/zend-validator/issues/102#issuecomment-262231016

**Comment by weierophinney** [comment]
@038291 You've actually just proven my point exactly. DKIM, SRV, DMARC, TLSA and such aren't hostnames. More info upon the subject; read the linked wikipedia article and try to read about DNS and how it works and what it's (im)possibilities are.

---

Originally posted by @CptChaos at https://github.com/zendframework/zend-validator/issues/102#issuecomment-262231772

**Comment by weierophinney** [comment]
@CptChaos  Leaves so that it is necessary to write the separate DNS RRSet's validator. Hostname validator isn't suitable for these purposes. Thanks.

ps: http://domainkeys.sourceforge.net/underscore.html

---

Originally posted by @038291 at https://github.com/zendframework/zend-validator/issues/102#issuecomment-262257831

**Comment by weierophinney** [comment]
This looks like a case for a new Domainkey validator

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-validator/issues/102#issuecomment-287286277

**Comment by weierophinney** [comment]
I solved this problem in a tricky way. I created an FqdnValidator. It has two options: allowUnderscore and allowWildcard. The FqdnValidator internally uses the Zend Hostname validator.

First, the FQDN string (e.g. abc.example.com) is split into the TLD (com), domain (example) and subdomain (abc) parts. It is a little bit against the official terminology, but what is important, is that the underscore as well as a wildcard (*) characters are only allowed for some DNS Records and only as a subdomain part.

So, when the allowUnderscore option is enabled, the underscore is replaced with 'x' character in all subdomains. The domain part (i.e. 'example') is not affected. The string is passed then to the Hostname validator.

When the allowWildcard option is enabled, each subdomain part is checked if it contains only one character and this character is the asterix (*). If this assertion is ok, the asterix is replaced with 'x' and passed to the Hostname validator.

The hardest thing to do here is to split the FQDN into the parts. For instance, some TLDs contain dot inside, i.e. in both cases example.de.com and example.com the domain name part is 'example'. You'll need to maintain the list of TLDs to achieve this splitting.

Sorry, but I can not share the solution I did because the FqdnValidator is a Symfony validator and the list of TLDs is loaded from the DB dynamically.

---

Originally posted by @crzdeveloper at https://github.com/zendframework/zend-validator/issues/102#issuecomment-307383801

**Comment by weierophinney** [comment]
@038291 Sorry for the late response. On the page you linked, you can also read:
> 'Names that **are not** host names can consist of any printable ASCII character.'

So yes, hostnames (like for web addresses) actually can't have a _ in them. ;)

@crzdeveloper How would you solve this when a subdomain has an x in it, like when you have example.example2.tld? ;) I would also no use a DB to store tld's, but rather configfiles or something similar. It's not likely TLD's are going to change much. ;) Keeping it from a DB makes it a bit faster, as you do not have to build another connection, query the database and wait for the results.

---

Originally posted by @CptChaos at https://github.com/zendframework/zend-validator/issues/102#issuecomment-307393844

**Comment by crzdeveloper** [comment]
@weierophinney 
So simpler said, before passing a hostname to the ZF/Laminas Hostname validator, I replace _ with x.

```
_tcp.example.com -> xtcp.example.com -> pass it to the hostname validator -> result is ok
abctcp.example.com -> abc.example.com -> pass it to the hostname validator -> result is ok
example.example2.tld -> example.example2.tld -> pass it to the hostname validator -> result is ok
```
And that's the trick. We use this hack in our DNS manager for validating the `service` part of the SRV record. So I'd say, underscores do not relate to the Hostname Validator almost at all :)

**Comment by crzdeveloper** [comment]
@weierophinney 
as for the question about where to store TLDs, I would not store them in the DB in the scope of the ZF/Laminas. What could be done, is something like the TldProvider strategy: there will be default implementation and who needs a better implementation, can pass their own into the validator constructor.

TLDs are changing, sometimes it can be critical if you sell domain names: you always need to keep the DB of TLDs and know in which phase they are. But that's another use-case which is not needed for IMHO 99.9% of library users.

**Comment by gsteel** [comment]
This was fixed long ago…
