### ISSUE TITLE
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

### ISSUE THREAD

**Issue by oschildt** [laminas/laminas-validator#31]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.13.0 

#### Summary

When using "composer update" on my project, I started to get the warning:

Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

I investigated and found out that you include this package in this file

laminas/laminas-validator/composer.json

#### Current behavior

The  "composer update" operation issues the warning.

#### How to reproduce

Create a dummy composer project and write in the composer.json

  "require": {
    ...
    "laminas/laminas-http": ">=2.11.2"
    ...
  },

then do "composer update".

#### Expected behavior

No warning should be issued.

**Comment by Xerkus** [comment]
It is expected and can be safely ignored. Essentially, it is a deprecation warning.

Interop interface extends psr interface and can be safely used where psr is expected.  However, interop removal requires new major release as it is a BC break.

**Comment by michalbundyra** [comment]
See also @weierophinney explanation here:
https://github.com/zendframework/zend-eventmanager/issues/79#issuecomment-562228837
and @Ocramius here:
https://github.com/zendframework/zend-mvc-i18n/issues/23#issuecomment-563918061

**Comment by augustofagioli** [comment]
> It is expected and can be safely ignored.

As Drupal 8  site-builder, i faced this installing drush. Please understand my point of view: you are actually asking me too much. Composer added lots of extra time and work.Sorry for my moaning :)
