### ISSUE TITLE
[RFC]: Deprecate and remove the `Upload` validator

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-validator#347]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 3.0.0  |
| BC Break?           | Yes |

### Goal

Remove seeimingly unnecessary validator

### Background

There are 2 validators for validating successful upload:

- https://github.com/laminas/laminas-validator/blob/2.61.x/src/File/Upload.php
- https://github.com/laminas/laminas-validator/blob/2.61.x/src/File/UploadFile.php

`UploadFile` accepts a value to `isValid` representing a single file and returns true when the file appears to be successfully uploaded.

`Upload` requires a list of all uploaded files to its constructor, and subsequent calls to `isValid` represent the form element name/key it seems. i.e. `isValid('myfile')`

It seems odd that `Upload` needs the input as an argument to its constructor (Or option) rather than to the `isValid` method.

### Considerations

I might be missing the point of the `Upload` validator. It looks like something from the days of `Laminas\File\Transfer` and `Laminas\Http`.

If anyone can shed any light on why it works the way it does, I'm all ears.

### Proposal(s)

Deprecate the validator in 2.61.0 and remove it in 3.0.0

cc @laminas/technical-steering-committee 

Edit: The `Upload` validator works directly with the `$_FILES` super-global 🤢

**Comment by froschdesign** [comment]
@weierophinney 
> ### Considerations
> I might be missing the point of the `Upload` validator. It looks like something from the days of `Laminas\File\Transfer` and `Laminas\Http`.
> 
> If anyone can shed any light on why it works the way it does, I'm all ears.

Do you have a comment on this?

**Comment by gsteel** [comment]
Closed via #362
