### ISSUE TITLE
Date::convertString() - return a more appropriate message for non-existent date. 

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-validator#39]
For example, for input date of '2016-02-31', the error message of FALSEFORMAT - "The input does not fit the date format Y-m-d" is included in the return, which is not very descriptive, even a bit misleading.

The actual 'warnings' message from `DateTime::getLastErrors()` is "The parsed date was invalid".

Proposal: 
- Add `const NONEXISTENT    = 'dateNonExistent';`
- In `$messageTemplates`, add `self::NONEXISTENT  => "The date does not exist";` or `self::NONEXISTENT  => "No such day in calendar";`
- In `convertString()`, use `$this->error(self::NONEXISTENT);` instead of `$this->error(self::FALSEFORMAT);`

---

Originally posted by @SBC-Fujian at https://github.com/zendframework/zend-validator/issues/85

**Comment by gsteel** [comment]
Closing as stale
