### ISSUE TITLE
Local EmailAdress Validator Problems (Windows)

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-validator#42]
Hey there!

If i attach following validator to my validator chain and validate emails like `xxx@web.de` or `xxx@googlemail.com` or simply my own domain i will get the `Validator\EmailAddress::INVALID_SEGMENT` message printed.

``` php
new Validator\EmailAddress(
    [
        'useDeepMxCheck' => true,
        'useDomainCheck' => true,
        'useMxCheck'     => true
    ]
)
```

I debugged the code and found out that the call of `$result = getmxrr($this->idnToAscii($this->hostname), $mxHosts, $weight);` in method `validateMXRecords()` will return true but the `$mxHosts` and `$weight` is empty. Thats why the `isValid()` return `false`. I tested it under Windows, linux and Macintosh. Linux and Macintosh works great but Windows fails.

I tried to use `$result = dns_get_record($this->idnToAscii($this->hostname), DNS_MX, $mxHosts, $weight);` instead but then my php-cgi quits.

**Linux/Macintosh:**

``` console
php -r '$mxHosts = [];$weight  = [];$result = getmxrr("googlemail.com", $mxHosts, $weight);var_dump($result, $mxHosts, $weight);'
bool(true)
array(5) {
  [0]=>
  string(31) "alt1.gmail-smtp-in.l.google.com"
  [1]=>
  string(31) "alt4.gmail-smtp-in.l.google.com"
  [2]=>
  string(31) "alt3.gmail-smtp-in.l.google.com"
  [3]=>
  string(31) "alt2.gmail-smtp-in.l.google.com"
  [4]=>
  string(26) "gmail-smtp-in.l.google.com"
}
array(5) {
  [0]=>
  int(10)
  [1]=>
  int(40)
  [2]=>
  int(30)
  [3]=>
  int(20)
  [4]=>
  int(5)
}
```

**Windows:**

``` console
php -r '$mxHosts = [];$weight  = [];$result = getmxrr("googlemail.com", $mxHosts, $weight);var_dump($result, $mxHosts, $weight);'
bool(true)
array(0) {
}
array(0) {
}
```

---

Originally posted by @FabianKoestring at https://github.com/zendframework/zend-validator/issues/68

**Comment by michalbundyra** [comment]
Am i the only person who has that strange behavior.

---

Originally posted by @FabianKoestring at https://github.com/zendframework/zend-validator/issues/68#issuecomment-279634417

**Comment by apteles** [comment]
A litle search in php documention we see that a following note:

 ![screenshot](https://user-images.githubusercontent.com/31255210/78464463-68aa2180-76c0-11ea-982b-ae19714f064b.png)

The question is this, the validation should care about platform that is running and then show some warning that requires the installation of  **Net_DNS**?

One possible solution is:
```
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
    // do something here!
}
```

**Comment by gsteel** [comment]
Closing as stale
