### ISSUE TITLE
Feature request: Add support for PSR7

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-validator#43]
Add support for `Psr\Http\Message\UploadedFileInterface` for `Zend\Validator\File\*` validators.

---

Originally posted by @svycka at https://github.com/zendframework/zend-validator/issues/62

**Comment by michalbundyra** [comment]
Is there any progress on this already? Till then I have to use the plain $_FILES array for the validators mentioned above.


---

Originally posted by @BWorld at https://github.com/zendframework/zend-validator/issues/62#issuecomment-246172498

**Comment by michalbundyra** [comment]
No progress at this point; feel free to submit a patch if you need it sooner rather than later. :wink:


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-validator/issues/62#issuecomment-246361709

**Comment by michalbundyra** [comment]
No problem, $_FILES work as well.

I would like to do some contribution to a framework I have been using for several years now.
Whenever I have time I could look into it, write some tests for it etc.

As the title suggests 'add support' everything should be backward compatible? Could do that and keep all current tests working. Later on when the major version increases we could remove the BC code from the implementation. 

Let me know how you think about the BC part.


---

Originally posted by @BWorld at https://github.com/zendframework/zend-validator/issues/62#issuecomment-246941027

**Comment by dbierer** [comment]
Shouldn't this issue be closed?  It looks like the `getFileInfo()` method defined in `Laminas\Validator\File\FileInformationTrait`, used by most of the file validators, already checks to see if the supplied value is an instance of `Psr\Http\Message\UploadedFileInterface` and extracts the information accordingly.  The only thing really missing is that the ability to accept an `UploadedFileInterface` is not mentioned in the doc block.
