### ISSUE TITLE
Let AbstractDb implement AdapterAwareInterface

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-validator#46]
At the moment `Zend\Validator\Db\AbstractDb` has a method `setAdapter` to set the database adapter. I think the canonical way of doing that would be to implement the `Zend\Db\Adapter\AdapterAwareInterface`'s `setDbAdapter()` instead, maybe by using the `Zend\Db\Adapter\AdapterAwareTrait`.

---

Originally posted by @larsnystrom at https://github.com/zendframework/zend-validator/issues/32

**Comment by michalbundyra** [comment]
We haven't done this in the past as the `AdapterAwareInterface` was added _after_ the validator was created. :)

As for the `AdapterAwareTrait`, until 2.5, we couldn't have used it.

Feel free to send a PR with these changes.


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-validator/issues/32#issuecomment-127221414

**Comment by michalbundyra** [comment]
Has this been fixed yet ? If not I would like to give it a try .


---

Originally posted by @Keops92 at https://github.com/zendframework/zend-validator/issues/32#issuecomment-162488316

**Comment by michalbundyra** [comment]
https://github.com/zendframework/zend-validator/pull/46


---

Originally posted by @Keops92 at https://github.com/zendframework/zend-validator/issues/32#issuecomment-162507410

**Comment by michalbundyra** [comment]
it close-able


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-validator/issues/32#issuecomment-189837288

**Comment by simivar** [comment]
@michalbundyra, this one has been already implemented:
https://github.com/laminas/laminas-validator/blob/master/src/Db/AbstractDb.php#L25-L27

**Comment by michalbundyra** [comment]
@simivar, thanks.
