### ISSUE TITLE
Duplicated factory definition for Laminas\I18n\Validator\IsInt in Laminas\Validator\ValidatorPluginManager

### ISSUE THREAD

**Issue by devision-milen-dzhambazov** [laminas/laminas-validator#78]
### Bug Report

|    Q            |   A
|------------ | ------
| Version(s)  | 2.13.4

#### Summary

There is a duplicated factory definition for Laminas\I18n\Validator\IsInt in Laminas\Validator\ValidatorPluginManager on lines 368 and 373.

#### Current behavior

The factory definition is duplicated.

#### How to reproduce

Open src/ValidatorPluginManager.php and go to lines 368 and 373.

#### Expected behavior

There should be only one factory definition for the same class.

**Comment by froschdesign** [comment]
This problem is already fixed with #68 and will be released with version [2.13.5](https://github.com/laminas/laminas-validator/milestone/4).

Thanks for your help, though.
