### ISSUE TITLE
Missing Idns changes?

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-validator#9]
Back when ZF1 diverged from ZF2:
* Canada: https://github.com/zendframework/zf1/blob/d31af76036c9b95eea00f1d3ec4d4262cce2fbf2/library/Zend/Validate/Hostname.php#L1368
* Serbia: https://github.com/zendframework/zf1/blob/d31af76036c9b95eea00f1d3ec4d4262cce2fbf2/library/Zend/Validate/Hostname.php#L1452
* Germany: https://github.com/zendframework/zf1/commit/d08473b3

---

Originally posted by @robocoder at https://github.com/zendframework/zend-validator/issues/217

**Comment by gsteel** [comment]
Stale issue - no idea what the issue is actually about.
