### ISSUE TITLE
File extension comparison treats some distinct extensions as equal

### ISSUE THREAD

**Issue by Zenexer** [laminas/laminas-validator#98]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | HEAD (2.15.x)

#### Summary

Certain file extensions are considered equal by validators in some contexts.  For example, `Laminas\Validator\File\ExcludeExtension#isValid` will treat file extensions `10` and `010` as equal (`example.10` and `example.010` have the same file extension in its eyes).  This is a result of using `==` and `in_array()` without strict mode to check strings.  The following both return true in PHP:

```php
'10' == '010';
in_array('10', ['010']);
```

#### Expected behavior

`example.10` should never be considered to have the file extension `010`.

**Comment by fgsl** [comment]
https://github.com/laminas/laminas-validator/pull/104

**Comment by gsteel** [comment]
Closed via #355
